[build]
  base = "packages/frontend"
  publish = "dist"
  command = "npm run test:ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=../.."

[context.production]
  command = "npm run test:ci && npm run build"

[context.deploy-preview]
  command = "npm run test:ci && npm run build"

[context.branch-deploy]
  command = "npm run test:ci && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
