name: Frontend Tests

on:
  push:
    branches: [main, develop]
    paths: 
      - 'packages/frontend/**'
      - '.github/workflows/test-frontend.yml'
  pull_request:
    branches: [main]
    paths: 
      - 'packages/frontend/**'
      - '.github/workflows/test-frontend.yml'

jobs:
  test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm ci -w packages/frontend
        
      - name: Run ESLint
        run: npm run lint -w packages/frontend
        
      - name: Run TypeScript check
        run: npx tsc -b packages/frontend --noEmit
        
      - name: Run unit tests
        run: npm run test:unit -w packages/frontend
        env:
          NODE_ENV: test
          
      - name: Run integration tests  
        run: npm run test:integration -w packages/frontend
        env:
          NODE_ENV: test
          
      - name: Run all tests with coverage
        run: npm run test:coverage -w packages/frontend
        env:
          NODE_ENV: test
          
      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./packages/frontend/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Frontend Test Coverage Report
          
      - name: Build frontend
        run: npm run build -w packages/frontend
        env:
          NODE_ENV: production
          
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm ci -w packages/frontend
          
      - name: Run security audit
        run: npm audit --audit-level moderate -w packages/frontend
        
      - name: Run dependency check
        run: npx audit-ci --config .audit-ci.json -w packages/frontend || true